### ISSUE TITLE
rrtools::use_circleci() gives an error

### ISSUE THREAD

**Issue by wolass** [benmarwick/rrtools#106]
**Please wait for some discussion of your report before making a Pull Request.**

**Describe the bug**
circleci does not build due to the wrong url. it has a repeated "//" in it

> * Turn on circleci for your repo at https://circleci.com/gh//wolass
>   and add your environment variables: DOCKER_EMAIL, 
>   DOCKER_USER, DOCKER_PASS.

see the "gh//wolass" <- this needs to read "gh/wolas"

**To Reproduce**

1. Start a new project using the rrtools methods described in the https://github.com/benmarwick/rrtools/blob/master/README.md file. 
2. in step 6. after using ` rrtools::use_circleci(docker_hub = FALSE)` you will reproduce the error
3. The webpage will open with a wrong address - 404 error

**Expected behavior**

One should expect that the repo will be visible in circleci  under the proper address and the the webpage that is getting open is not containing repeated //

**Comment by wolass** [comment]
Also... Im new to circle ci... but It seems like there has been an update to config version 2.0 and the previous projects are no longer supported. 

I think we need an update in rrtools for the circle.ci pipeline (I have failed to succeed although I followed the rrtools documentation.

**Comment by benmarwick** [comment]
Thanks for posting this, yes, I think your conclusion is correct. We need to catch up with the circle-ci 2.0 config format. I've used it on some [other repos](https://github.com/benmarwick/ArchaeoGLOBE/blob/master/.circleci/config.yml), so I have a slight familiarity  with it.

**Comment by benmarwick** [comment]
I've removed circle-ci from rrtools for now, since GitHub Actions has become very versatile.
