### ISSUE TITLE
[feature] reproducible pdf builds

### ISSUE THREAD

**Issue by joukewitteveen** [benmarwick/rrtools#108]
Word of warning: This issue came up at an interesting talk by @annakrystalli. I have no time to help out, but she encouraged me to post this regardless.

The gold standard for reproducibility in software is to be able to produce bitwise identical outputs. If we can produce an artifact with the exact same checksum as the artifact published online, we are pretty sure to have reproduced it.

When using `rrtools` to produce papers in PDF, the template
https://github.com/benmarwick/rrtools/blob/6bbe6c2cd8a9f2df0de1326acde1cc4b9b5eab07/inst/templates/paper.Rmd
is inadequate for making the PDF reproducible in the above sense of being bitwise identical. This is largely because of the presence of timestamps inside the PDF. There are ways to overcome this (see: https://tex.stackexchange.com/questions/229605/reproducible-latex-builds-compile-to-a-file-which-always-hashes-to-the-same-va/313605#313605). It would be nice if `rrtools` provided support for this. It must be possible to convince bookdown to include a few extra lines in the intermediate LaTeX code.

**Comment by benmarwick** [comment]
This is a very interesting observation, and I do see what you mean about how timestamps break the bitwise reproducibility of the PDF and other outputs. We would welcome some TeX expertise on implementing this!
