### ISSUE TITLE
Create GitHub Repo did not worked on Mac

### ISSUE THREAD

**Issue by MartinHinz** [benmarwick/rrtools#11]
While trying out the workflow during lunchtime today on @nmueller18 mac, Creating GitHub repository resulted in

`Fehler in stop(github_error(req)) : Not Found (404)`

We had to create the repo by hand and had to use git remote add statt` instead of `git remote set-url`.

Could not find a pull request solving that issue, so it might remain a problem. From my Arch machine, everything went well regarding this.

**Comment by benmarwick** [comment]
Can you please update with the output of `sessionInfo()`?

**Comment by MartinHinz** [comment]
Will do asap, currently Kiel university has no Internet :-(

**Comment by MartinHinz** [comment]
So, it is not from that very session, unfortunately, but I am not sure that this would be much more informative:

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0  
```

**Comment by benmarwick** [comment]
Could it be the case that no internet connection was the problem in the first case? Can you try to repeat the error on an OSX machine that you know is connected to a good internet?

**Comment by MartinHinz** [comment]
Unfortunately not today, since @nmueller18 is already on his way home. Might be due to internet, but problem occured only after lunch. He is mentioned, so he should receive and probably is willing to repeat tomorrow?

**Comment by benmarwick** [comment]
ok, no problem. We can write tests for travis to run on OSX, but test a function that uses the GitHub API is a bit awkward to automate. We'll just wait for Nils to try again another day!

**Comment by nmueller18** [comment]
I have just tried it on my Mac at home with virtually the same setup (see below), and everything went smoothly (even the trick with the shell was not necessary). The only annoyance from my point of view is the fact that RStudio creates the new project directory inside the currently active project. Thus, the user should be warned to close any open projects. In my case the directory was then created in the top-level of my user account.

R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0

**Comment by benmarwick** [comment]
Thanks for the follow up. I agree about that annoyance. I've added some text for the first step to be more clear about setting the path for the new project. Are we ok to close this, or do you want to test more on OSX?

**Comment by nmueller18** [comment]
I will test it again on my office-Mac and report.

**Comment by benmarwick** [comment]
ok, thanks. FWIW, I haven't had `devtools::use_github` work properly at all for me in RStudio on Windows, on two different machines. From the R GUI it works fine. But in RStudio it always errors after making the GitHub repo.

**Comment by nmueller18** [comment]
Now, everything worked fine on my office-Mac as well, so the issue can be closed (I cannot do it).

**Comment by benmarwick** [comment]
Ok, thanks!
