### ISSUE TITLE
Better documentation of required software and instructions to reproduce paper

### ISSUE THREAD

**Issue by annakrystalli** [benmarwick/rrtools#111]
**Please wait for some discussion of your request before making a Pull Request.** 

**Is your feature request related to a problem? Please describe.**

The feature relates to experiences we are uncovering during the N8 Reprohack series. 

While the requirement for R and RStudio is fairly obvious to R users, we have had non-R users approach R projects and get stuck not knowing what software this all runs on.  And while a user of `rrtools` might know to go the `analysis` folder and open `paper.Rmd`, someone unfamiliar with the framework coming across the compendium might not know how to navigate it and which files to inspects. 

**Describe the solution you'd like**

In the template README **installation** section, include something like:

> This Research Compendium has been developed using the statistical programming language R.  To work with the compendium, you will need the following installed on your computer:
>
> 1. the [R software](https://cran.r-project.org/mirrors.html) itself
> 2. _Optional_ [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/#download).

Additionally, it might be useful to include a section in the README on how to reproduce the paper which could default to: 
> Open `analysis/paper/paper.Rmd` and **knit** (in Rstudio) or run `rmarkdown::render("analysis/paper/paper.Rmd")` in the R console

**Comment by benmarwick** [comment]
Yes, this seems like a very reasonable addition, let's do it!
