### ISSUE TITLE
Binder: Failed to connect to event stream

### ISSUE THREAD

**Issue by d-paulus** [benmarwick/rrtools#117]
Getting a "Failed to connect to event stream" error when trying to start my repo (https://github.com/d-paulus/rambfunddata) in Binder. Also receiving same error when trying to start the rrtools main repo in Binder. Tried refreshing the Binder page after the error, tried wiping browser cache & cookies, and tried using Chrome, Firefox, Edge.

**Comment by benmarwick** [comment]
Hi @d-paulus thanks for letting us know, this is most likely something going on the binder service, which we can't control much, or at all, with rrools. But we have a few options for how we can start binder, maybe we need to try some of the others.

**Comment by homer3018** [comment]
Just bumped into this issue, as binder seems to be not working for me at the moment:
```
Step 7/8 : RUN wget https://github.com/benmarwick/rrtools/raw/master/DESCRIPTION && R -e "devtools::install_deps()"
 ---> Running in aa7ee8aed706
--2020-09-17 20:34:22--  https://github.com/benmarwick/rrtools/raw/master/DESCRIPTION
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/benmarwick/rrtools/master/DESCRIPTION [following]
--2020-09-17 20:34:22--  https://raw.githubusercontent.com/benmarwick/rrtools/master/DESCRIPTION
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1288 (1.3K) [text/plain]
DESCRIPTION.1: Permission denied

Cannot write to ‘DESCRIPTION.1’ (Success).
Removing intermediate container aa7ee8aed706
The command '/bin/sh -c wget https://github.com/benmarwick/rrtools/raw/master/DESCRIPTION && R -e "devtools::install_deps()"' returned a non-zero code: 3
```

**Comment by benmarwick** [comment]
@homer3018 thanks, I'm also getting this error. If you have any insights about why we're seeing this, please let us know.

**Comment by homer3018** [comment]
Sorry I can't help on this one. I just wanted to try it out as I'm willing to transition to rrtools, so I can understand the basics of it and get going :).
Great work btw !

**Comment by benmarwick** [comment]
Thanks, no worries, I set the binder dockerfile back to pull a slightly earlier version of R in https://github.com/benmarwick/rrtools/commit/d091ec15c0512634d52f49b5583d46baca9e5677 and that seems to have fixed it. Perhaps we are just too much on the cutting edge here 😂
