### ISSUE TITLE
Populate Dockerfile's MANTAINER automatically based on DESCRIPTION

### ISSUE THREAD

**Issue by eliocamp** [benmarwick/rrtools#128]
Now `use_dockerfile()` uses a template and asks the user to fill the rest. One of the things that could be pre-populated is the MAINTAINER part. It's a reasonable default to use the maintainer role stated in the DESCRIPTION file if there is one.

**Comment by benmarwick** [comment]
Thank you, this sounds like a great idea. Another option could be to use the git username and email stored in gitconfig, which I think is what we use to populate the DESCRIPTION. Would you like to propose a pull request that does something like this?

**Comment by eliocamp** [comment]
Yeah, no problem! There you go!
