### ISSUE TITLE
`create_compendium()` does not "move us into the new project"

### ISSUE THREAD

**Issue by ntrlshrp** [benmarwick/rrtools#133]
**Please wait for some discussion of your report before making a Pull Request.**

**Describe the bug**
`create_compendium("/home/UserName/DeleteThisRrtoolsPackage")` from GitHub (`d091ec1`) does one of two things:
- If you use the function while RStudio is inside a project (e.g., "DeleteThisDockerPackage")
  - Writes into "DeleteThisDockerPackage" directory (possibly over files) and only creates `.gitignore`, `.Rbuildignore`, `DESCRIPTION`, `NAMESPACE`, and `DeleteThisRrtoolsPackage.Rproj` in `/home/UserName/DeleteThisRrtoolsPackage`
- If you use the function while RStudio is **NOT** inside a project (e.g., from working directory (`getwd()`): `/home/UserName`)

```
Error: Path '/home/UserName/' does not appear to be inside a project or package.
In addition: Warning message:
In path_file(base_path) : restarting interrupted promise evaluation
```

I think this stems from `rrtools/R/core_create_compendium.R` lines 21-22, where `setwd(pkgname)` is commented:
```
  # move us into the new project
  # setwd(pkgname)
```

**To Reproduce**

- Outside a project:
1. Launch Docker container, `docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/verse:3.6.3`
2. Login to `localhost:8787` on your browser with username: `rstudio` and password: `<YOUR_PASS>`
3. Enter `remotes::install_github("benmarwick/rrtools")` in the RStudio console
4. Enter `rrtools::create_compendium("/home/rstudio/DeleteThisRrtoolsPackage")` in the RStudio console

- Inside a project (after the above "Outside a project"):
5. Click `Project: (None)` in the upper right of RStudio IDE
6. Click `New Project > New Directory > R Package`
7. Name it "DeleteThisDockerPackage" and click `Create New Package`
8. Enter `rrtools::create_compendium("/home/rstudio/DeleteThisRrtoolsPackage")` in the RStudio console

**Expected behavior**
`rrtools::create_compendium()` should put all `rrtools` template files into the new `rrtools` package directory and leave the starting directory untouched.

**Comment by nevrome** [comment]
Good spotting! Thanks for reporting this. 

@benmarwick Why did you comment `setwd(pkgname)` in 3ba7334d52709597d44586f0c374d6f9b0a45eae? Was this on purpose?
