### ISSUE TITLE
Innacurate README instruction for MIT License

### ISSUE THREAD

**Issue by FlukeAndFeather** [benmarwick/rrtools#136]
Step 2 of "How to Use" in the [README](https://github.com/benmarwick/rrtools#2-usethisuse_mit_licensename--my-name) uses the parameter `name` in `usethis::use_mit_license()` but the [correct parameter](https://usethis.r-lib.org/reference/licenses.html) is `copyright_holder`.

**Comment by benmarwick** [comment]
Thanks @nevrome!
