### ISSUE TITLE
use_analysis() fails when data_in_git = FALSE

### ISSUE THREAD

**Issue by FlukeAndFeather** [benmarwick/rrtools#137]
Calling `use_analysis(data_in_git = FALSE)` produces the error `Error in usethis::ui_done("Adding ", paths, " to ", file.path(directory,  : 
  unused arguments (" to ", file.path(directory, ".gitignore"))`. 

The source of the error is [core_use_analysis.R:59](https://github.com/benmarwick/rrtools/blob/d091ec15c0512634d52f49b5583d46baca9e5677/R/core_use_analysis.R#L55), which says `if (!data_in_git) use_git_ignore("*/data/*")`. Calling `use_git_ignore("*/data/*")` reproduces the error. So I think [helpers_git.R:186](https://github.com/benmarwick/rrtools/blob/d091ec15c0512634d52f49b5583d46baca9e5677/R/helpers_git.R#L186) needs to be changed.

Note: reprex() produces a different error, otherwise I'd include it.

**Comment by wolass** [comment]
Oh... I usually just use `usethis::use_github`. Good catch.

**Comment by benmarwick** [comment]
Thanks for letting us know, this is an important feature, I think so I'll take a look
