### ISSUE TITLE
Binder won't launch for R >= 4.0.0

### ISSUE THREAD

**Issue by frederic-santos** [benmarwick/rrtools#139]
**Describe the bug**
Not sure if this is really a bug or something I did not understand well. However, when taking the `rrtools` repo "as is" and just changing all occurrences of **R 3.6.0** by any member of the **R 4.0.x** family (in particular [in the binder configuration](https://github.com/benmarwick/rrtools/blob/master/.binder/Dockerfile)), I cannot launch binder properly. Instead, the docker image is pulled and seems to build normally, but after a while I just get:
`500 : Internal Server Error. The error was: could not start rstudio in time`
and Rstudio server is not displayed within my browser.

**To Reproduce**
* An example here: https://github.com/frederic-santos/rrtools
* The bug report was also made here quite a long time ago: https://github.com/karthik/binder-test/issues/8

I understand that, if this is really a bug, this would be better to file this issue into the [rocker](https://github.com/rocker-org/rocker) repository, but I just wanted to know whether someone else has already faced the same issue.

Thanks!

**Comment by benmarwick** [comment]
Thank you, yes I have also noticed this. I'm not sure there's much we can do about it here in the rrtools repository. Do you have any suggestions?

**Comment by frederic-santos** [comment]
Thanks!
First I can follow this issue to Dirk Eddelbuettel to check the "rocker" side, and I will keep you informed of his answer.

**Comment by benmarwick** [comment]
I made a work-around by having use_readme_rmd generate a runtime.txt file, following the example here. Please try it and let me know how you go!
