### ISSUE TITLE
runtime.txt leads to R CMD CHECK note

### ISSUE THREAD

**Issue by FlukeAndFeather** [benmarwick/rrtools#143]
**Please wait for some discussion of your report before making a Pull Request.**

**Describe the bug**
`rrtools::create_compendium()` by default creates runtime.txt in the top level directory. This causes a note in R CMD CHECK (Non-standard file/directory found at top level).

**To Reproduce**

I don't know how to make a reprex for this bug because it creates a new RStudio project, but if you call `rrtools::create_compendium("path/to/an/empty/directory)"` then, in the new project, call `devtools::check()` you'll get the note.

**Expected behavior**
No notes. I think this is an easy fix: when runtime.txt is created, add it to .Rbuildignore.

**Comment by benmarwick** [comment]
Thanks for bringing this up, and your proposed solution sounds spot on. You're warmly welcome to make a pull request, or we can do it.

**Comment by benmarwick** [comment]
Can you make a pull request so we can include your excellent fix here? We will also add you as a named contributor in the DESCRIPTION of the pkg. Thank you!
