### ISSUE TITLE
Error in `create_compendium()` if usethis<2.0.0

### ISSUE THREAD

**Issue by FlukeAndFeather** [benmarwick/rrtools#144]
**Please wait for some discussion of your report before making a Pull Request.**

**Describe the bug**
`create_compendium()` throws the error `` if usethis<2.0.0. This is because the parameter to `use_mit_license()` changed from `name` to `copyright_holder` in version 2.0.0 (see usethis [NEWS](https://cran.r-project.org/web/packages/usethis/news/news.html)).

See also #136 

**To Reproduce**

On a system with usethis<2.0.0, call `create_compendium()`.

**Expected behavior**
No error.

**Comment by FlukeAndFeather** [comment]
I'm writing a pull request that fixes this by checking the version of usethis and using the appropriate parameter name accordingly. An alternative fix would be to make usethis>=2.0.0 a dependency. I lean towards the former because it doesn't change the user's system. But happy to go the DESCRIPTION route instead if you'd prefer.

**Comment by benmarwick** [comment]
Thank you, this sounds like a great idea!

**Comment by benmarwick** [comment]
We have `copyright_holder` in all the relevant places now
