### ISSUE TITLE
Package with dot in name not captured by rrtools::add_dependencies_to_description()

### ISSUE THREAD

**Issue by see24** [benmarwick/rrtools#146]
I am using the package `spatstats.geom` and it was missed by `rrtools::add_dependencies_to_description()` I think because of the "." in the package name. Could that be fixed in the regex here? (Sorry I don't have the regex skills to confidently suggest how)

https://github.com/benmarwick/rrtools/blob/3f830bce55e733f17e599a632a4e930ee82b8edb/R/core_manage_dependencies.R#L136

**Comment by nevrome** [comment]
#145 should address that - could you check the PR @benmarwick?

**Comment by benmarwick** [comment]
Thanks so much for spotting this @see24 and @nevrome for the quick fix! I have checked the PR and tested it locally and it addresses the issue, thank you again. @see24 do let us know if you have any further issues.
