### ISSUE TITLE
Don't open new session with `rrtools::use_compendium()`

### ISSUE THREAD

**Issue by eliocamp** [benmarwick/rrtools#151]
Using `rrtools::use_compendium()` on a new project re-opens the project in a new RStudio window. This can be confusing and, worse, it hides the excellent guided steps that show you which next steps you need to perform.

**Comment by benmarwick** [comment]
Yes, I understand what you mean. If there is another way to open an RStudio project without this new window, I would be glad to know more about it. Do let me know what you think!

We could re-display the instructions in the new project, as one way to make this step less disorienting.

**Comment by benmarwick** [comment]
Closing this to due lack of activity.
