### ISSUE TITLE
Additional files required for submissions - Cover letter, COI, Graphical abstract

### ISSUE THREAD

**Issue by wolass** [benmarwick/rrtools#153]
**Please wait for some discussion of your request before making a Pull Request.** 

**Is your feature request related to a problem? Please describe.**
I am currently submitting a paper in Journal of Allergy and Clinical Immunology (written of course totally in `rrtools`).
Again, I need to be reminded upon submission to write the Cover Letter, provide Conflict of Interest Forms from my coauthors and prepare the graphical abstract. 

**Describe the solution you'd like**
As these practices are to my knowledge nearly universal nowadays in scientific journals we could optimize the file structure in our analysis folder. My suggestion would be to include the cover letter during the initial file generation process and have at least a placeholder for the graphical abstract in the figures folder that would be included in the paper.Rmd template (this could be optional if you think that graphical abstract is not universal, with the option argument `use_graphical_abstract = TRUE`). 

I have more problems with the COI forms. A quick search for ICMEJ COI package for R gave no relevant results. 
I think that the ICMEJ COI has become a well respected standard throught the years. I think automating the Conflict of interest Forms would reduce time for submitting papers. What I do not know however is if we should do that inside `rrtools`. 
Nevertheless, a file for COI would be needed (or as the simplest option: we should consider adding a paragraph about COI in the `paper.qmd` file).

**Describe alternatives you've considered**
Alternatively these files would have to be supplied through an external functions or packages. 

**Additional context**

**Comment by benmarwick** [comment]
I agree that cover letters and other documents are necessary for submission. My opinion is that they are out of scope for rrtools because they typically don't include any numerical or graphical output generated by R. I can imagine that a graphical abstract could be a plot or multiple plots produced by R, but I observe they are usually a composite of data viz and non-data viz, so I'm not sure that they can be entirely produced in R, so far as I see.
