### ISSUE TITLE
Binder offline

### ISSUE THREAD

**Issue by Irazall** [benmarwick/rrtools#155]
Thank you for writing this package! My PhD deals with replication in economics and I want to give this package a try. I recognized that your Binder example seems to be offline:
https://mybinder.org/v2/gh/benmarwick/rrtools/master?urlpath=rstudio

Is it possible to restart the service?
Thank you in advance!

**Comment by benmarwick** [comment]
I've just tried it now and it seems to be working, I can see RStudio in my browser. I've found Binder can be a little hit and miss, unfortunately I don't have access to directly restart its servers, so I usually just try again when the first attempt fails. Let me know how you go!

**Comment by Irazall** [comment]
No it seems to work for me as well. Thanks for checking! Hope that it stays online :)
