### ISSUE TITLE
output error in command "rrtools::use_readme_qmd()"

### ISSUE THREAD

**Issue by morfogeno** [benmarwick/rrtools#158]
trying for the first time the rrtools.  After issuing the following command I got the error:

rrtools::use_readme_qmd()

Error in glue_data(.x = NULL, ..., .sep = .sep, .envir = .envir, .open = .open,  : 
  is.environment(.envir) is not TRUE

Searching in the internet, probably is something related to an update of glue package. I tried again after installing the package using the following command but didn't change the output:

install.packages("glue")

**Comment by benmarwick** [comment]
Hi @morfogeno,

Thanks for your note, I was able to reproduce your error. It looks like there was a change in how the glue function behaves. I've pushed an update that I believe fixes this. Could you please install the current version and let me know how you go? Thank you so much.

Ben

**Comment by morfogeno** [comment]
Sure! Thank you for the very good software!


Em quarta-feira, 16 de outubro de 2024, Ben Marwick <
***@***.***> escreveu:

**Comment by morfogeno** [comment]
so after re-installation I ran again and everything worked seamless!

Only that I followed your wiki for recreating the github repository and got an error when running "rrtools::use_readme_rmd()". Then I read the github README.md where it says the command is "rrtools::use_readme_qmd()" and it worked great. I suggest you update the wiki.

PS-Suggestion: It would be invaluable if there were a tutorial showing how to run a concrete workflow. For instance, would I have to use renv from the beginning to work or could I do it later only if I need: I found a very good one for rcompendium (attached below):

https://epiverse-trace.github.io/research-compendium/reproducible.html.

Thanks again for your work.

**Comment by morfogeno** [comment]
so after re-installation I ran again and everything worked seamless!

Only that I followed your wiki for recreating the github repository and got
an error when running "rrtools::use_readme_rmd()". Then I read the github
README.md where it says the command is "rrtools::use_readme_qmd()" and it
worked great. I suggest you update the wiki.

PS - Suggestion: It would be invaluable if there were a tutorial showing
how to run a concrete workflow. For instance:

   1. would I have to use renv from the beginning so it works or could I do
   it later only when/if I need?
   2. If I add new folder inside analysis folder (say a R folder for my
   scripts) will the dependencies be tracked?

I found a very good one for rcompendium (attached below):
https://epiverse-trace.github.io/research-compendium/reproducible.html.

Thanks again for your work.

**Comment by benmarwick** [comment]
Hi @morfogeno,

Great to hear you had success, and thanks for your suggestions, those are very helpful. To answer your questions directly, I think renv can be added right at the end, as active development of the project winds down. If it's added earlier it can add some friction that feels necessary, in my experience. This assumes that everyone working on the project has the most recent versions of packages during the time they are actively working on it. 

Yes, if you add a new folder, renv can find it and track libraries mentioned in there. 

That's great that you found https://github.com/FRBCesab/rcompendium, that's a very nice project, it has a lot in common with rrtools, with some more features and great documentation.
