### ISSUE TITLE
Thesis and book templates

### ISSUE THREAD

**Issue by benmarwick** [benmarwick/rrtools#23]
Perhaps https://github.com/ismayc/thesisdown for a thesis and just https://github.com/rstudio/bookdown-demo for a book?

Do we simply have `use_analysis(structure = c("paper", "thesis", "book"))` and then, depending on the choice, create either:

* a `paper/` directory, as we currently do, or a 
* a `thesis/` directory, using https://github.com/ismayc/thesisdown, or a 
*  a `book/` directory, using https://github.com/rstudio/bookdown-demo

Does this seem like the right way to provide these options?

**Comment by dakni** [comment]
This sounds good. I currently use bookdown and at yesterday's ISAAK meeting the "single-file-content-structure" was requested. I need to have a more detailed look at thesisdown in order to really see the differences between book and thesis.

**Comment by benmarwick** [comment]
Made a start on this by adding the [thesisdown](https://github.com/ismayc/thesisdown/) thesis template in 52b37ef982821112baf03890916457e0c31fbe0e. It already has a tex template, which should make it easier to replace with tex templates for other schools. 

Let's see if that's true, or if it's easier to start from the bookdown-demo for a new thesis template! Initial impression is that there is much variation between templates, and it may be better to simply use bookdown-demo. Thoughts and advice welcome!

**Comment by benmarwick** [comment]
For example, we'd want to be able to use the Keil Uni tex templates (are they here: http://www.se.informatik.uni-kiel.de/en/student-theses/hints/guidelines-for-seminars-and-student-theses I can't get the zip) and the UW templates (I previously used them with a student here: https://github.com/SeungkiKwak/Kwak_S_PhD_thesis/tree/master/inst/rmarkdown_template)

**Comment by benmarwick** [comment]
We will redirect the user, via the readme, to huskydown and similar for thesis writing
