### ISSUE TITLE
Generate README references using .bib

### ISSUE THREAD

**Issue by pkq** [benmarwick/rrtools#28]
Should the references cited in the README get auto-generated from a `references.bib` file? It seems odd to advocate for that approach and then not use it, but perhaps I'm missing something?

I think this would require moving the Contributing section ahead of the references, unless there's a way to generate the references somewhere other than the end of the file?

**Comment by benmarwick** [comment]
Perhaps, sure. I mean, for this pkg I think it makes sense to have some references in the README, but for the packages today this package creates, I do not think we want references in those READMEs.

So we have a few meta-references here, to justify our approach, but we do not need those in the README we generate for the research compedium.

Is that what you were thinking?

**Comment by pkq** [comment]
Correct, this is just for `rrtools/README.Rmd`. Instead of including the references there by hand, add `bibliography:` and `csl:` lines to the YAML, and then reference them in the Rmd just as you would if this were a manuscript. Want me to give it a shot?
