### ISSUE TITLE
Differentiate between location options in use_analysis()

### ISSUE THREAD

**Issue by pkq** [benmarwick/rrtools#29]
As it stands, it isn't really clear why I might want to choose the `inst/` or `vignettes/` options in `use_analysis()`. Can you describe the relative advantages or disadvantages of each?

**Comment by benmarwick** [comment]
Yes, right. This is something I was planning to expand on in the vignette. The thread here https://github.com/ropensci/unconf17/issues/5 has the answers.

**Comment by pkq** [comment]
Ah, cool. Thanks, that's quite the thread!

**Comment by benmarwick** [comment]
We'll do this a vignette

**Comment by pkq** [comment]
Great, thanks!
