### ISSUE TITLE
Error: Could not find package root.

### ISSUE THREAD

**Issue by smuyengwa79** [benmarwick/rrtools#31]
Getting this error when I use: 

rrtools::use_analysis()

setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  English_United States.1252  
 tz       Africa/Johannesburg         
 date     2017-07-28                  

Packages ------------------------------------------------------------------------------
 package    * version    date       source                             
 backports    1.1.0      2017-05-22 CRAN (R 3.4.0)                     
 base       * 3.4.1      2017-06-30 local                              
 colorspace   1.3-2      2016-12-14 CRAN (R 3.4.0)                     
 compiler     3.4.1      2017-06-30 local                              
 curl         2.8.1      2017-07-21 CRAN (R 3.4.1)                     
 datasets   * 3.4.1      2017-06-30 local                              
 devtools   * 1.13.2     2017-06-02 CRAN (R 3.4.0)                     
 digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                     
 evaluate     0.10.1     2017-06-24 CRAN (R 3.4.0)                     
 ggplot2      2.2.1      2016-12-30 CRAN (R 3.4.0)                     
 git2r        0.19.0     2017-07-19 CRAN (R 3.4.1)                     
 graphics   * 3.4.1      2017-06-30 local                              
 grDevices  * 3.4.1      2017-06-30 local                              
 grid         3.4.1      2017-06-30 local                              
 gtable       0.2.0      2016-02-26 CRAN (R 3.4.0)                     
 htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)                     
 httr         1.2.1      2016-07-03 CRAN (R 3.4.0)                     
 knitr        1.16       2017-05-18 CRAN (R 3.4.0)                     
 lazyeval     0.2.0      2016-06-12 CRAN (R 3.4.0)                     
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                     
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                     
 methods    * 3.4.1      2017-06-30 local                              
 munsell      0.4.3      2016-02-13 CRAN (R 3.4.0)                     
 plyr         1.8.4      2016-06-08 CRAN (R 3.4.0)                     
 R6           2.2.2      2017-06-17 CRAN (R 3.4.0)                     
 Rcpp         0.12.12    2017-07-15 CRAN (R 3.4.1)                     
 rlang        0.1.1      2017-05-18 CRAN (R 3.4.0)                     
 rmarkdown    1.6        2017-06-15 CRAN (R 3.4.0)                     
 rprojroot    1.2        2017-01-16 CRAN (R 3.4.0)                     
 rrtools      0.1.0      2017-07-28 Github (benmarwick/rrtools@b9cf7f1)
 rstudioapi   0.6.0.9000 2017-07-28 Github (rstudio/rstudioapi@41dfa7f)
 scales       0.4.1      2016-11-09 CRAN (R 3.4.0)                     
 stats      * 3.4.1      2017-06-30 local                              
 stringi      1.1.5      2017-04-07 CRAN (R 3.4.0)                     
 stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)                     
 tibble       1.3.3      2017-05-29 Github (tidyverse/tibble@b2275d5)  
 tools        3.4.1      2017-06-30 local                              
 utils      * 3.4.1      2017-06-30 local                              
 whisker      0.3-2      2013-04-28 CRAN (R 3.4.0)                     
 withr        1.0.2      2016-06-20 CRAN (R 3.4.0)

**Comment by dakni** [comment]
Before running `use_analysis` you need to run 

 ```
use_compendium("PackageName")
```

as written in the readme. This will set up the general environment in which the analysis will take place.

**Comment by smuyengwa79** [comment]
Thanks that worked
