### ISSUE TITLE
README.Rmd won't allow pkgdown site to build

### ISSUE THREAD

**Issue by adamhsparks** [benmarwick/rrtools#36]
If using _pkgdown_ to build a site, the process fails with:

```r
Updating README.md
Error in (function (variant = "markdown_strict", preserve_yaml = FALSE,  : 
  unused argument (html_preview = FALSE)
```

Currently the YAML reads:

```
---
output:
  md_document:
    variant: markdown_github
---
```

changing the YAML to instead be:

```
output: github_document
```

builds the _pkgdown_site

**Comment by adamhsparks** [comment]
Is this related to the **Data** formatting?

I've just removed the bold formatting from it because of the automatic link that appears, how does that even happen?

**Comment by benmarwick** [comment]
Thanks, can you show me the exact lines that you ran just before you got that error message? I'd like to try and reproduce what you describe

**Comment by adamhsparks** [comment]
I just set up a dummy project to test it.

Following the directions in `rrtools` README.md file up to 

```r
rrtools::use_readme_rmd()
```

and then running

```r
pkgdown::build_site()
```

Recreated the error for me.

It's referred to here: https://github.com/hadley/pkgdown/issues/286

**Comment by benmarwick** [comment]
Thank, yes, that's great. Looking at the issue thread you mention, it seems that the omni-readme template that I took from devtools might be out of date since pkgdown appears. I'll try updating it with this one (https://github.com/r-lib/usethis/blob/master/inst/templates/omni-README) and test your code.

**Comment by benmarwick** [comment]
Ok, I've updated the readme template and can build the pkgdown site following your code above:

![clipboard01](https://user-images.githubusercontent.com/1262179/29762149-cc56cc2e-8b81-11e7-8c69-3badddb2db13.png)

Let me know how that works for you.

**Comment by adamhsparks** [comment]
Confirmed. Thanks @benmarwick
