### ISSUE TITLE
`open_data` not an assigned object

### ISSUE THREAD

**Issue by mrecos** [benmarwick/rrtools#39]
https://github.com/benmarwick/rrtools/blob/2d4f979dcadd36a427b421f6e50f9c1fe844f371/R/hello.R#L251

error in `use_analysis()` as `open_data` is not a parameter of an assigned object. Appears to be introduced in commit https://github.com/benmarwick/rrtools/commit/645e5f2279b7e286679a61b60f6047b2fae71eca#diff-bdd61cd30c99f724d7f7f90c10c94fd5
when `open_data` was changed to `data_in_git`

**Comment by benmarwick** [comment]
Thanks for spotting that!
