### ISSUE TITLE
integrate with rstudio projects template feature?

### ISSUE THREAD

**Issue by benmarwick** [benmarwick/rrtools#41]
Following [Matt's suggestion](https://twitter.com/metamattj/status/908049529768833025), consider this: https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html

**Comment by mrecos** [comment]
I think this is a really cool idea and is compatible with the rrtools package philosophy.  I tested this out a bit and while successful in creating a template and launching a new rrtools package, ran into the obvious hurdle.  The way in which `rrtools` starts a new RStudio session after `use_compendium()` breaks the function sequence.  Briefly, here are the ways that I came up with to approach this (by no means the only ways):

1.  have project template call an init function that calls `use_compendium()` and subsequent functions based on selections in UI.
2. have the template call an init function that calls a modified `use_compendium()` that includes calls to subsequent functions based on parameters passed to it from the UI
3. create a new function that executes on load once the new package is re-opened in RStudio. It will execute subsequent setup functions based on parameters read from a file passed in from the UI

So how is that working out?

1. Not good. Once `use_compendium()` is called, any subsequent function calls in the `init` functions error.
2. Pretty much the same as above. Perhaps some more room to work with this approach, but it suffers from trying to call functions on a workspace that is not yet open. Will have to think about it more.
3. Have not tried it and don't know how to run functions on project open, but there may be a way? that function would then readline the attributes from the `init` function and run subsequent setup function (e.g. `use_travis()`) to create the project as selected in the UI.

So there is room to work here and I will keep at it.

**Comment by mrecos** [comment]
Great progress thanks to the answers here:
https://community.rstudio.com/t/project-templates-and-rprofile/82

I have it working successfully to open the project template UI, select some options, the `init` script then digests the UI options and writes two file 1) `ProjectTemplate` a simple record of all the options passed from the UI, 2) a `.Rprofile` file that executes the subsequent `rrtools` functions and then renames itself to archive the setup script without interfering with operations later on. 
TO DO now is to get all the options in the UI and right the logic to test/check them.
issues:

- there is no pop-ups or validation features in the project template UI; it works or it doesn't.
- the prompts to ok file overwrites from `rrtools` could get in the way
- this will not handle complex or highly customized `rrtools` setups.

**Comment by benmarwick** [comment]
Thanks for these updates, this is great. Seems like RStudio 1.1 isn't quite ready for me, as I encounter a few problems when trying this template:

![rr1](https://user-images.githubusercontent.com/1262179/30608736-1f535d3a-9d2e-11e7-8897-a23b7fd2404c.png)

![rr2](https://user-images.githubusercontent.com/1262179/30608737-1f569a9a-9d2e-11e7-955c-cc69488e12e3.png)

![rr5](https://user-images.githubusercontent.com/1262179/30608732-1f3ff75e-9d2e-11e7-86b5-e569369471a4.png)

Some problem when creating from the template: 

![rr7](https://user-images.githubusercontent.com/1262179/30608733-1f4190aa-9d2e-11e7-82a6-03f54f6265ed.png)

Click OK and get another problem:

![rr8](https://user-images.githubusercontent.com/1262179/30608731-1f3f5920-9d2e-11e7-99f9-aa3109b5d775.png)

Try opening the project from the .RProj file that was created:

![rr9](https://user-images.githubusercontent.com/1262179/30608734-1f42bc5a-9d2e-11e7-93ea-b7efba6532ad.png)

I guess I need to wait for RStudio 1.1 to be more mature before I can enjoy this.

**Comment by benmarwick** [comment]
@mrecos it might be that RStudio is more robust with pkg templates now, would you like to see this can work now? Thank you!
