### ISSUE TITLE
[Question] References rendering in a specific position

### ISSUE THREAD

**Issue by wolass** [benmarwick/rrtools#45]
There might be a need to render the references before figures. Is there a way to specify the position where references should be inserted in the generated paper?

**Comment by fmichonneau** [comment]
You can use the chunk below in your rmarkdown document to insert the references where you want them.

```rmd
## References

<div id="refs"></div>
```

**Comment by wolass** [comment]
That did it! Thanks, add to documentation and we are closing this issue! :)
