### ISSUE TITLE
Keywords and highlights from the paper.Rmd file are not rendered into the docx file

### ISSUE THREAD

**Issue by wolass** [benmarwick/rrtools#50]
Whenever I render the paper.Rmd into Word these two fields are not showing:
```
keywords: |
  keyword 1; keyword 2; keyword 3
highlights: |
  These are the highlights. 
```

They are however visible in the HTML file.

**Comment by kguidonimartins** [comment]
A simple solution is to put the abstract and the keywords outside of the yaml. See an example [here](https://raw.githubusercontent.com/kguidonimartins/minimal-template/master/main-script.Rmd).

**Comment by benmarwick** [comment]
I think we need to modify the template to make these show up as expected.
