### ISSUE TITLE
replace devtools with usethis 

### ISSUE THREAD

**Issue by benmarwick** [benmarwick/rrtools#58]
Many of the helper functions in devtools now have more user-friendly implementations in usethis (more chatty feedback in the console, colour in the messages, etc.). Should we shift to `usethis::create` to support `rrtools::use_compendium("pkgname")` and `usethis::use_github` instead of `devtools::use_github`?

**Comment by SCSchmidt** [comment]
Because I really don't know much about this: Would there be any disadvantage in changing to `usethis`?

**Comment by benmarwick** [comment]
Seems that the developers of devtools have decided to stop improving some functions in that package (that we use here) and instead continue developing these functions in usethis. They feel that devtools has become too big and unfocused, so they propose usethis to take over many of the `use_* functions that initially appeared in devtools. 

The recent work in usethis is very good, nice friendly and chatty feedback messages in the terminal after running functions like setting up the github repo, etc. I think it's a good fit for rrtools. 

Disadvantage is a little work to edit our functions, that's all I can think of  ¯\_(ツ)_/¯ But maybe you guys can think of others?

**Comment by nevrome** [comment]
I think it's a good idea to switch to usethis. `devtools::create` is explicitly deprecated and should definitively be replaced. `usethis::use_github` also seems to be the better option. 

Unfortunately this functions are so complex and do so much stuff, that replacing them could break something in rrtools or render our current tests useless. I think we should just try this in a development branch. 

If you want we can split the work again, @benmarwick. I can offer to replace one function and test it.
