### ISSUE TITLE
Add a one-liner meta-function

### ISSUE THREAD

**Issue by benmarwick** [benmarwick/rrtools#64]
I had some feedback from @clanfear that it would be useful to have a single function that combines most of the steps. Like a meta-function. We could have 2-3 main options, e.g. 

- a very basic, lightweight compendium suitable for student assignments,      
- a more elaborate one, and then      
- the kitchen sink with CI and docker for example.

I think this meta-function could be useful in workshop lessons where we don't have time to review every step in detail, but where we want to give a quick taste of how to do reproducibile research easily.

What do you think?

**Comment by MartinHinz** [comment]
I think we had some discussions about that already. There were some opponents to that meta-function, I would like to remember you. But personally I very much see (more than) a good use case for that.

**Comment by nevrome** [comment]
A wizard for a wizard collection...

I think we should create such a function to guide the user through the complete process. And also an [RStudio-Addin](https://rstudio.github.io/rstudioaddins/).

**Comment by benmarwick** [comment]
Wow, that add-in is great!

**Comment by nevrome** [comment]
Great that you found the time to implement the metafunction! 

Maybe we could keep this issue still open for some time: I'm working on this addin idea -- admittedly very slowly.

**Comment by nevrome** [comment]
This thing became to complex. I decided to create an extra package for it: https://github.com/nevrome/rrtools.addin

Let's see if an addin like this turns out to be useful. I guess it's aimed at **very** new users.

**Comment by benmarwick** [comment]
We now have this in `create_compendium("pkgname")`
