### ISSUE TITLE
hadley/requirements

### ISSUE THREAD

**Issue by nevrome** [benmarwick/rrtools#65]
@dakni and I wrote the `add_dependencies_to_description()` function to search the code in the repository for package dependencies. I've just seen that @hadley started to work on a package to do exactly this. I expect it to be or at least to become more sophisticated than our function. 

This issue is supposed to be a reminder that we could replace and improve our function in the future relying on [hadley/requirements](https://github.com/hadley/requirements).

**Comment by benmarwick** [comment]
Yes, I saw that. I like your function because it works really well, and means we don't need additional dependencies. Well, let's see how Hadley's pkg develops and if it gets any amazing features that make it irresistible.

**Comment by hadley** [comment]
FWIW requirements is being pulled out of packrat so we can have one canonical system for determining package dependencies. The goal is to keep requirements low-dependency so it can be easily used by other packages.

**Comment by nevrome** [comment]
@hadley That sound's good! Do you have a timetable for this project? I guess you will provide a CRAN release?

@benmarwick IMHO we could do with some more carefully selected dependencies. rrtools is a very high level package anyway.
