### ISSUE TITLE
The use of unexported/internal functions called via ::: is not allowed by CRAN

### ISSUE THREAD

**Issue by nevrome** [benmarwick/rrtools#70]
We get a new NOTE in the check results:

```
* checking dependencies in R code ... NOTE
Unexported objects imported by ':::' calls:
  ‘usethis:::done’ ‘usethis:::field’ ‘usethis:::git_uncommitted’
  ‘usethis:::todo’ ‘usethis:::value’
  See the note in ?`:::` about the use of this operator.
```

We have four options to deal with this:

1. Ignore it. A CRAN release would be difficult though.
2. Contact the usethis package authors and ask them to export these functions.
3. Copy the function source code (and cite the author).
4. This nasty workaround: https://stat.ethz.ch/pipermail/r-devel/2013-August/067210.html

**Comment by benmarwick** [comment]
Yes, thanks for raising this, and summarizing the options so nicely. Should we take a vote about what do to?

**Comment by nevrome** [comment]
Haha - now I'm really curious about the result of a survey. 

I personally suggest to copy/reimplement the code. I believe all of these five functions are very small and simple helpers. And as far as I remember rrtools already contains initially foreign code.

**Comment by benmarwick** [comment]
Thanks, we're now using the newly exported functions from usethis, and we have a local custom version of `git_uncommitted()`
