### ISSUE TITLE
openProject

### ISSUE THREAD

**Issue by nevrome** [benmarwick/rrtools#8]
The call to `openProject` via `rstudioapi::callFun()` only works in the newer RStudio Versions (and of course not if your not using RStudio). Maybe we should add a check whether the function is called from a up to date RStudio version and only run `rstudioapi::callFun("openProject", paste0("./", path))` in that case. 

[The openProject and initializeProject functions were added in version 1.1.287 of RStudio.](https://rdrr.io/github/rstudio/rstudioapi/man/projects.html)

**Comment by dakni** [comment]
sounds reasonable. We could check the version in the current call of `rstudioapi` and change

```
if(rstudioapi::isAvailable())
```

to

```
if(rstudioapi::isAvailable() & rstudioapi::getVersion() >= xxx)
```

However, I am not sure how to "compare" certain version. The output of getVersion has two classes "package_version" and "numeric_version". How to access these?

**Comment by MartinHinz** [comment]
Sorry, was not aware of the issues... So, #10 should be a workaround.

**Comment by benmarwick** [comment]
Good spotting! I've used @MartinHinz's suggestion of `browseURL` for now, in 33e2c824b26b835a27a34716a68fb4c075d253f8
