### ISSUE TITLE
Allow symlinks in `use_compendium()`

### ISSUE THREAD

**Issue by antass** [benmarwick/rrtools#80]
When initiating a new compendium with:

```
rrtools::use_compendium("~/path/to/new/compendium")
```
where `~/path/to/new` is a symlink to `/some/other/path`, `rrtools` throws an error:

```
> rrtools::use_compendium("~/path/to/new/compendium")
Error: '/home/nfs/user.name/path/to/new' is not a directory.
```

However, replacing symlink with full path works:

```
rrtools::use_compendium("/some/other/path/compendium")
```

**Comment by nevrome** [comment]
Thanks for pointing this out, @antass.

`rrtools::use_compendium` is only a wrapper function for `usethis::create_package` to add some checks, messages and interactivity. The error you're reporting stems from in `usethis::create_package`. I suggest you report it [here](https://github.com/r-lib/usethis/issues) to inform the usethis developers. If they fix the issue, then it will work in rrtools as well.

**Comment by nevrome** [comment]
@antass Did you open an issue in the usethis repository?

**Comment by antass** [comment]
@nevrome Just did. Thanks for the reminder. Feel free to close this.

**Comment by nevrome** [comment]
Ah - great. https://github.com/r-lib/usethis/issues/794

We can reopen the issue if, contrary to expectations, they should send you back.
