### ISSUE TITLE
docker login email flag not found

### ISSUE THREAD

**Issue by sahirbhatnagar** [benmarwick/rrtools#87]
I received an unknown flag error when trying to login to dockerhub using the `-e` flag as used in this line of the docker template:
https://github.com/benmarwick/rrtools/blob/f2e3b43f9e25455d4a89972982d2ed44099fbd37/inst/templates/travis.yml-with-docker#L22

The error went away when I removed the `-e` flag. Here is the [`docker login` man page](https://docs.docker.com/engine/reference/commandline/login/) I referred to which doesn't have the `-e` or `--email` flag anywhere.  

I don't know how to make a reproducible example of this. I could create a PR if newer users of `rrtools` are experiencing the same issue.

**Comment by benmarwick** [comment]
Hi Sahir, thanks, that's a great observation! I also see here https://github.com/docker/docker-ce/releases/tag/v17.06.0-ce that the email flag has been removed from that function. 

Please do go ahead with a PR to remove this from the template, thanks!
