### ISSUE TITLE
use_compendium is overriding `Authors@R` set as usethis.description option

### ISSUE THREAD

**Issue by annakrystalli** [benmarwick/rrtools#95]
**Please wait for some discussion of your request before making a Pull Request.** 

**Is your feature request related to a problem? Please describe.**
At the minute, `use_compendium()` overwrites the `Authors@R` field I have set in my profile for the `usethis.description` option which seems to make redundant both setting the `usethis.description` as the default for the `fields` argument and indeed the provision of that argument as it seems most of the fields will be overwritten.

**Describe the solution you'd like**
Perhaps only override `Authors@R` it if it's empty or maybe not a valid person specification?

**Comment by benmarwick** [comment]
Good spotting! I've pushed a fix that checks for options in the `.Rprofile` and uses those for Authors@R if they are present. Thanks for spotting this!
