### ISSUE TITLE
Travis build using docker fails if compendium name contains capital letters

### ISSUE THREAD

**Issue by annakrystalli** [benmarwick/rrtools#98]
**Please wait for some discussion of your report before making a Pull Request.**

**Describe the bug**

The default specification of variable `$REPO` in the `travis.yml` created using `rrtools::use_travis(docker=T)` causes the build to fail on TRAVIS because of an invalid tag format if the compendium name contains capital letters. Logs return the following error so it seems that docker hub does not accept capitals in tags. 
```
invalid argument "[secure]/rrcompendiumRSE19" for t: invalid reference format: repository name must be lowercase
See 'docker build --help'.
```
This could be problematic as compendium naming is already restricted so not allowing capitals in compendium names is not ideal.

**To Reproduce**
Here's the [logs](https://travis-ci.org/annakrystalli/rrcompendiumRSE19/builds/583604982) of a TRAVIS build of a compendium showing the error, with the [travis.yml](https://github.com/annakrystalli/rrcompendiumRSE19/blob/b8563638467e8dd4f3a117742bf93a3e33cf46f0/.travis.yml) in the default state.

**Expected behavior**

I fixed the error by assigning an all lower case version of `$REPO`  in my `.travis.yml` as such: `REPO="$(echo $DOCKER_USER/rrcompendiumRSE19 | tr A-Z a-z)"`

See [full `.travis.yml`](https://github.com/annakrystalli/rrcompendiumRSE19/blob/master/.travis.yml) that works.

Would be great to include this tweak in the template as it took me a couple of hours to figure out and fix and may well be an issue many end up encountering. Perhaps as:

```
REPO="$(echo $DOCKER_USER/{{{repo}}} | tr A-Z a-z)"
```
in the `travis.yml-with-docker` template.

(beware `REPO` is defined twice in the template)

Look forward to your thoughts

**Comment by annakrystalli** [comment]
Actually I thought of a really simple and small fix that could address this issue. Have a little look at #100 and let me know what you think. Worked for my compendium! 😃

**Comment by benmarwick** [comment]
Let's try it! I know you have a workshop very soon (and I'm doing another one in Japan today)

**Comment by annakrystalli** [comment]
I can write a test too if you like.
